### ISSUE TITLE
Add Semiphore 'Lock' Controller/Model/Routes

### ISSUE THREAD

**Issue by chronosis** [DealersLinkDevTeam/dealerslink-api#2]
Functionality for Semiphore 'Locks' need to be created and added to the new REST API.  These should include --

GetLock(lockName, userID) -- Reports on a lock
CreateLock(lockName, userID) -- Create and reports on a lock
RefreshLock(lockName, userID) -- Refresh the expiration on a lock
ReleaseLock(lockName, userID) -- Release and Delete a lock

**Comment by rafaelsalomon** [comment]
* GetLock(lockName,lockExpirationInSeconds,timeoutInSeconds) ==> lockID
* RenewLock(lockName,lockID)
* ReleaseLock(lockName,lockID)

**Comment by rafaelsalomon** [comment]
@chronosis the lock timestamps are now in utc

**Comment by chronosis** [comment]
This is an obsolete repo, and was setup only until we had an official repo, I'm migrating the comments into the official repo
